#!/usr/bin/env python3
"""
Round-4 seed: full AWS catalog + Azure/GCP/Cisco foundation gaps + Zero2Automated.
Reuses make_cert from seed_round_2.

Run: python3 scripts/seed_round_4_catalog.py
"""
import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "scripts"))
from seed_round_2 import make_cert  # noqa

SPECS = [
    # ---------------- AWS catalog (active 2026) ----------------
    {"id": "aws.aif-c01", "vendor_slug": "aws", "vendor_name": "Amazon Web Services", "vendor_url": "https://aws.amazon.com/certification/", "name": "AWS Certified AI Practitioner", "abbr": "AIF-C01", "slug": "aif-c01", "domain": "governance-risk", "secondary_domains": ["cloud-security", "privacy-data-protection"], "official_url": "https://aws.amazon.com/certification/certified-ai-practitioner/", "third_party_source": "pearsonvue-aws", "third_party_url": "https://www.pearsonvue.com/us/en/aws.html", "cost_usd": 100, "tier_hint": "foundational", "summary": "Foundational validation of AI/ML and generative AI concepts on AWS.", "family": "vendor-cloud", "experience_years": 0},
    {"id": "aws.saa-c03", "vendor_slug": "aws", "vendor_name": "Amazon Web Services", "vendor_url": "https://aws.amazon.com/certification/", "name": "AWS Certified Solutions Architect - Associate", "abbr": "SAA-C03", "slug": "saa-c03", "domain": "security-architecture", "secondary_domains": ["cloud-security"], "official_url": "https://aws.amazon.com/certification/certified-solutions-architect-associate/", "third_party_source": "niccs", "third_party_url": "https://niccs.cisa.gov/education-training/catalog/intellectual-point/amazon-aws-certified-solutions-architect-associate", "cost_usd": 150, "tier_hint": "associate", "summary": "Designs distributed, resilient, cost-optimized AWS architectures.", "family": "vendor-cloud", "experience_years": 1},
    {"id": "aws.dva-c02", "vendor_slug": "aws", "vendor_name": "Amazon Web Services", "vendor_url": "https://aws.amazon.com/certification/", "name": "AWS Certified Developer - Associate", "abbr": "DVA-C02", "slug": "dva-c02", "domain": "application-appsec", "secondary_domains": ["cloud-security"], "official_url": "https://aws.amazon.com/certification/certified-developer-associate/", "third_party_source": "pearsonvue-aws", "third_party_url": "https://www.pearsonvue.com/us/en/aws.html", "cost_usd": 150, "tier_hint": "associate", "summary": "Develops, deploys, and debugs cloud-native AWS applications.", "family": "vendor-cloud", "experience_years": 1},
    {"id": "aws.soa-c03", "vendor_slug": "aws", "vendor_name": "Amazon Web Services", "vendor_url": "https://aws.amazon.com/certification/", "name": "AWS Certified CloudOps Engineer - Associate", "abbr": "SOA-C03", "slug": "soa-c03", "domain": "cloud-security", "secondary_domains": ["network-defense", "security-architecture"], "official_url": "https://aws.amazon.com/certification/certified-cloudops-engineer-associate/", "third_party_source": "pearsonvue-aws", "third_party_url": "https://www.pearsonvue.com/us/en/aws.html", "cost_usd": 150, "tier_hint": "associate", "summary": "Deploys, manages, and operates multi-account AWS workloads with IaC and containers.", "family": "vendor-cloud", "experience_years": 1},
    {"id": "aws.dea-c01", "vendor_slug": "aws", "vendor_name": "Amazon Web Services", "vendor_url": "https://aws.amazon.com/certification/", "name": "AWS Certified Data Engineer - Associate", "abbr": "DEA-C01", "slug": "dea-c01", "domain": "privacy-data-protection", "secondary_domains": ["cloud-security"], "official_url": "https://aws.amazon.com/certification/certified-data-engineer-associate/", "third_party_source": "pearsonvue-aws", "third_party_url": "https://www.pearsonvue.com/us/en/aws.html", "cost_usd": 150, "tier_hint": "associate", "summary": "Builds and operates secure data pipelines and lakes on AWS.", "family": "vendor-cloud", "experience_years": 2},
    {"id": "aws.mla-c01", "vendor_slug": "aws", "vendor_name": "Amazon Web Services", "vendor_url": "https://aws.amazon.com/certification/", "name": "AWS Certified Machine Learning Engineer - Associate", "abbr": "MLA-C01", "slug": "mla-c01", "domain": "application-appsec", "secondary_domains": ["cloud-security", "privacy-data-protection"], "official_url": "https://aws.amazon.com/certification/certified-machine-learning-engineer-associate/", "third_party_source": "pearsonvue-aws", "third_party_url": "https://www.pearsonvue.com/us/en/aws.html", "cost_usd": 150, "tier_hint": "associate", "summary": "Builds, deploys, and operationalizes ML pipelines on AWS.", "family": "vendor-cloud", "experience_years": 1},

    # ---------------- Microsoft Azure foundation ----------------
    {"id": "microsoft.az-900", "vendor_slug": "microsoft", "vendor_name": "Microsoft", "vendor_url": "https://learn.microsoft.com/credentials/", "name": "Microsoft Certified: Azure Fundamentals (AZ-900)", "abbr": "AZ-900", "slug": "az-900", "domain": "cloud-security", "secondary_domains": ["governance-risk"], "official_url": "https://learn.microsoft.com/credentials/certifications/azure-fundamentals/", "third_party_source": "pearsonvue-microsoft", "third_party_url": "https://www.pearsonvue.com/us/en/microsoft.html", "cost_usd": 99, "tier_hint": "foundational", "summary": "Foundational understanding of Azure cloud services, pricing, and security.", "family": "vendor-cloud", "experience_years": 0},
    {"id": "microsoft.ai-900", "vendor_slug": "microsoft", "vendor_name": "Microsoft", "vendor_url": "https://learn.microsoft.com/credentials/", "name": "Microsoft Certified: Azure AI Fundamentals (AI-900)", "abbr": "AI-900", "slug": "ai-900", "domain": "governance-risk", "secondary_domains": ["privacy-data-protection"], "official_url": "https://learn.microsoft.com/credentials/certifications/azure-ai-fundamentals/", "third_party_source": "pearsonvue-microsoft", "third_party_url": "https://www.pearsonvue.com/us/en/microsoft.html", "cost_usd": 99, "tier_hint": "foundational", "summary": "Foundational AI/ML concepts on Azure (retires 2026-06-30).", "family": "vendor-cloud", "experience_years": 0},
    {"id": "microsoft.dp-900", "vendor_slug": "microsoft", "vendor_name": "Microsoft", "vendor_url": "https://learn.microsoft.com/credentials/", "name": "Microsoft Certified: Azure Data Fundamentals (DP-900)", "abbr": "DP-900", "slug": "dp-900", "domain": "privacy-data-protection", "secondary_domains": ["cloud-security"], "official_url": "https://learn.microsoft.com/credentials/certifications/azure-data-fundamentals/", "third_party_source": "pearsonvue-microsoft", "third_party_url": "https://www.pearsonvue.com/us/en/microsoft.html", "cost_usd": 99, "tier_hint": "foundational", "summary": "Foundational data concepts on Azure relational, NoSQL and analytics workloads.", "family": "vendor-cloud", "experience_years": 0},
    {"id": "microsoft.az-204", "vendor_slug": "microsoft", "vendor_name": "Microsoft", "vendor_url": "https://learn.microsoft.com/credentials/", "name": "Microsoft Certified: Azure Developer Associate (AZ-204)", "abbr": "AZ-204", "slug": "az-204", "domain": "application-appsec", "secondary_domains": ["cloud-security", "iam"], "official_url": "https://learn.microsoft.com/credentials/certifications/azure-developer/", "third_party_source": "pearsonvue-microsoft", "third_party_url": "https://www.pearsonvue.com/us/en/microsoft.html", "cost_usd": 165, "tier_hint": "associate", "summary": "Develops cloud applications and services on Azure (retires 2026-07-31).", "family": "vendor-cloud", "experience_years": 2},
    {"id": "microsoft.az-700", "vendor_slug": "microsoft", "vendor_name": "Microsoft", "vendor_url": "https://learn.microsoft.com/credentials/", "name": "Microsoft Certified: Azure Network Engineer Associate (AZ-700)", "abbr": "AZ-700", "slug": "az-700", "domain": "network-defense", "secondary_domains": ["cloud-security", "security-architecture"], "official_url": "https://learn.microsoft.com/credentials/certifications/azure-network-engineer-associate/", "third_party_source": "pearsonvue-microsoft", "third_party_url": "https://www.pearsonvue.com/us/en/microsoft.html", "cost_usd": 165, "tier_hint": "associate", "summary": "Designs and implements Azure networking, hybrid connectivity, and security.", "family": "vendor-cloud", "experience_years": 2},
    {"id": "microsoft.ms-102", "vendor_slug": "microsoft", "vendor_name": "Microsoft", "vendor_url": "https://learn.microsoft.com/credentials/", "name": "Microsoft 365 Certified: Administrator Expert (MS-102)", "abbr": "MS-102", "slug": "ms-102", "domain": "iam", "secondary_domains": ["endpoint-mobile", "cloud-security"], "official_url": "https://learn.microsoft.com/credentials/certifications/m365-administrator-expert/", "third_party_source": "pearsonvue-microsoft", "third_party_url": "https://www.pearsonvue.com/us/en/microsoft.html", "cost_usd": 165, "tier_hint": "expert", "summary": "Manages M365 tenants, identity, security, compliance, and Copilot administration.", "family": "vendor-cloud", "experience_years": 3},

    # ---------------- Google Cloud foundation + role-based ----------------
    {"id": "google.gen-ai-leader", "vendor_slug": "google", "vendor_name": "Google Cloud", "vendor_url": "https://cloud.google.com/learn/certification", "name": "Google Cloud Generative AI Leader", "abbr": "GenAI Leader", "slug": "gen-ai-leader", "domain": "governance-risk", "secondary_domains": ["privacy-data-protection"], "official_url": "https://cloud.google.com/learn/certification/generative-ai-leader", "third_party_source": "pearsonvue-google", "third_party_url": "https://googlecloudexamstore.pearsonvue.com/", "cost_usd": 99, "tier_hint": "foundational", "summary": "Foundational, business-focused validation of generative AI strategy on Google Cloud.", "family": "vendor-cloud", "experience_years": 0},
    {"id": "google.ace", "vendor_slug": "google", "vendor_name": "Google Cloud", "vendor_url": "https://cloud.google.com/learn/certification", "name": "Google Cloud Associate Cloud Engineer", "abbr": "ACE", "slug": "ace", "domain": "cloud-security", "secondary_domains": ["iam"], "official_url": "https://cloud.google.com/learn/certification/cloud-engineer", "third_party_source": "pearsonvue-google", "third_party_url": "https://googlecloudexamstore.pearsonvue.com/", "cost_usd": 125, "tier_hint": "associate", "summary": "Deploys and operates GCP solutions; foundational hands-on credential.", "family": "vendor-cloud", "experience_years": 1},
    {"id": "google.pcd", "vendor_slug": "google", "vendor_name": "Google Cloud", "vendor_url": "https://cloud.google.com/learn/certification", "name": "Google Cloud Professional Cloud Developer", "abbr": "PCD", "slug": "pcd", "domain": "application-appsec", "secondary_domains": ["cloud-security"], "official_url": "https://cloud.google.com/learn/certification/cloud-developer", "third_party_source": "pearsonvue-google", "third_party_url": "https://googlecloudexamstore.pearsonvue.com/", "cost_usd": 200, "tier_hint": "professional", "summary": "Builds scalable, secure cloud-native apps on Google Cloud.", "family": "vendor-cloud", "experience_years": 3},
    {"id": "google.pcdo", "vendor_slug": "google", "vendor_name": "Google Cloud", "vendor_url": "https://cloud.google.com/learn/certification", "name": "Google Cloud Professional Cloud DevOps Engineer", "abbr": "PCDO", "slug": "pcdo", "domain": "cloud-security", "secondary_domains": ["application-appsec", "incident-forensics"], "official_url": "https://cloud.google.com/learn/certification/cloud-devops-engineer", "third_party_source": "pearsonvue-google", "third_party_url": "https://googlecloudexamstore.pearsonvue.com/", "cost_usd": 200, "tier_hint": "professional", "summary": "Implements SRE, CI/CD, and observability on Google Cloud.", "family": "vendor-cloud", "experience_years": 3},
    {"id": "google.pcdb", "vendor_slug": "google", "vendor_name": "Google Cloud", "vendor_url": "https://cloud.google.com/learn/certification", "name": "Google Cloud Professional Cloud Database Engineer", "abbr": "PCDB", "slug": "pcdb", "domain": "privacy-data-protection", "secondary_domains": ["cloud-security"], "official_url": "https://cloud.google.com/learn/certification/cloud-database-engineer", "third_party_source": "pearsonvue-google", "third_party_url": "https://googlecloudexamstore.pearsonvue.com/", "cost_usd": 200, "tier_hint": "professional", "summary": "Designs, migrates, and manages enterprise databases on Google Cloud.", "family": "vendor-cloud", "experience_years": 3},
    {"id": "google.pde", "vendor_slug": "google", "vendor_name": "Google Cloud", "vendor_url": "https://cloud.google.com/learn/certification", "name": "Google Cloud Professional Data Engineer", "abbr": "PDE", "slug": "pde", "domain": "privacy-data-protection", "secondary_domains": ["cloud-security"], "official_url": "https://cloud.google.com/learn/certification/data-engineer", "third_party_source": "pearsonvue-google", "third_party_url": "https://googlecloudexamstore.pearsonvue.com/", "cost_usd": 200, "tier_hint": "professional", "summary": "Designs and operates data processing systems with security and governance on GCP.", "family": "vendor-cloud", "experience_years": 3},
    {"id": "google.pmle", "vendor_slug": "google", "vendor_name": "Google Cloud", "vendor_url": "https://cloud.google.com/learn/certification", "name": "Google Cloud Professional Machine Learning Engineer", "abbr": "PMLE", "slug": "pmle", "domain": "application-appsec", "secondary_domains": ["privacy-data-protection", "cloud-security"], "official_url": "https://cloud.google.com/learn/certification/machine-learning-engineer", "third_party_source": "pearsonvue-google", "third_party_url": "https://googlecloudexamstore.pearsonvue.com/", "cost_usd": 200, "tier_hint": "professional", "summary": "Designs, builds, and productionizes ML models on Google Cloud.", "family": "vendor-cloud", "experience_years": 3},

    # ---------------- Cisco foundation networking ladder ----------------
    {"id": "cisco.ccna", "vendor_slug": "cisco", "vendor_name": "Cisco", "vendor_url": "https://www.cisco.com/site/us/en/learn/training-certifications/", "name": "Cisco Certified Network Associate (CCNA)", "abbr": "CCNA", "slug": "ccna", "domain": "network-defense", "secondary_domains": ["security-architecture"], "official_url": "https://www.cisco.com/site/us/en/learn/training-certifications/certifications/enterprise/ccna/index.html", "third_party_source": "niccs", "third_party_url": "https://niccs.cisa.gov/training/catalog/tace/ccna", "cost_usd": 300, "tier_hint": "associate", "summary": "Foundational networking, IP services, security and automation (200-301 v1.1).", "family": "vendor-network", "experience_years": 1},
    {"id": "cisco.ccnp-enterprise", "vendor_slug": "cisco", "vendor_name": "Cisco", "vendor_url": "https://www.cisco.com/site/us/en/learn/training-certifications/", "name": "Cisco Certified Network Professional Enterprise", "abbr": "CCNP Enterprise", "slug": "ccnp-enterprise", "domain": "network-defense", "secondary_domains": ["security-architecture"], "official_url": "https://www.cisco.com/site/us/en/learn/training-certifications/certifications/enterprise/ccnp-enterprise/index.html", "third_party_source": "niccs", "third_party_url": "https://niccs.cisa.gov/training/catalog/ets/cisco-ccnp-enterprise-encor", "cost_usd": 400, "tier_hint": "professional", "summary": "Enterprise networking design and operation (350-401 ENCOR + concentration).", "family": "vendor-network", "experience_years": 3},
    {"id": "cisco.ccie-enterprise-infrastructure", "vendor_slug": "cisco", "vendor_name": "Cisco", "vendor_url": "https://www.cisco.com/site/us/en/learn/training-certifications/", "name": "Cisco Certified Internetwork Expert Enterprise Infrastructure", "abbr": "CCIE EI", "slug": "ccie-enterprise-infrastructure", "domain": "network-defense", "secondary_domains": ["security-architecture"], "official_url": "https://www.cisco.com/site/us/en/learn/training-certifications/certifications/enterprise/ccie-enterprise-infrastructure/index.html", "third_party_source": "pearsonvue-cisco", "third_party_url": "https://www.pearsonvue.com/us/en/cisco.html", "cost_usd": 1900, "tier_hint": "expert", "summary": "Expert-level enterprise infrastructure design and 8-hour lab.", "family": "vendor-network", "experience_years": 7},
    {"id": "cisco.devnet-associate", "vendor_slug": "cisco", "vendor_name": "Cisco", "vendor_url": "https://www.cisco.com/site/us/en/learn/training-certifications/", "name": "Cisco Certified DevNet Associate (CCNA Automation)", "abbr": "DEVASC", "slug": "devnet-associate", "domain": "application-appsec", "secondary_domains": ["network-defense"], "official_url": "https://www.cisco.com/site/us/en/learn/training-certifications/exams/ccnaauto.html", "third_party_source": "pearsonvue-cisco", "third_party_url": "https://www.pearsonvue.com/us/en/cisco.html", "cost_usd": 300, "tier_hint": "associate", "summary": "Network automation and software dev on Cisco platforms (200-901, rebranded CCNA Automation).", "family": "vendor-network", "experience_years": 1},
    {"id": "cisco.devnet-professional", "vendor_slug": "cisco", "vendor_name": "Cisco", "vendor_url": "https://www.cisco.com/site/us/en/learn/training-certifications/", "name": "Cisco Certified DevNet Professional (CCNP Automation)", "abbr": "DEVCOR", "slug": "devnet-professional", "domain": "application-appsec", "secondary_domains": ["network-defense"], "official_url": "https://learningnetwork.cisco.com/s/autocor-exam-topics", "third_party_source": "pearsonvue-cisco", "third_party_url": "https://www.pearsonvue.com/us/en/cisco.html", "cost_usd": 400, "tier_hint": "professional", "summary": "Professional-level network programmability (350-901 AUTOCOR, rebranded CCNP Automation).", "family": "vendor-network", "experience_years": 3},

    # ---------------- Zero2Automated (malware analysis) ----------------
    {"id": "zero2automated.zar", "vendor_slug": "zero2automated", "vendor_name": "Zero2Automated", "vendor_url": "https://courses.zero2auto.com/", "name": "Zero2Automated Certified Reverse Engineer", "abbr": "ZAR", "slug": "zar", "domain": "incident-forensics", "secondary_domains": ["threat-intel"], "official_url": "https://courses.zero2auto.com/p/zero2automated-malware-analysis-course", "third_party_source": "vx-underground", "third_party_url": "https://vx-underground.org/", "cost_usd": 945, "tier_hint": "expert", "summary": "Practical malware reverse engineering exam: unpacking, custom packer analysis, and full report.", "family": "practical-defensive", "experience_years": 3},
]


def main() -> int:
    written = []
    skipped = []
    for spec in SPECS:
        rel_path, cert = make_cert(spec)
        if rel_path.exists():
            skipped.append(str(rel_path.relative_to(ROOT)))
            continue
        rel_path.parent.mkdir(parents=True, exist_ok=True)
        rel_path.write_text(json.dumps(cert, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
        written.append(str(rel_path.relative_to(ROOT)))
    print(f"wrote {len(written)} new cert files")
    if skipped:
        print(f"skipped {len(skipped)} existing files")
    return 0


if __name__ == "__main__":
    sys.exit(main())
